services:
  app: &app
    build:
      context: .
      args:
        REACT_API_URL: http://127.0.0.1:3000
        # For production testing
        # Must also be added to the runtime environment variables below, since Docker uses separate variables for build / runtime
        # RAILS_ENV: production
        # BUNDLE_DEPLOYMENT: 1
        # BUNDLE_WITHOUT: "development test" # Note that this must be added to the runtime environment variables below as well
    command: ["./bin/rails", "server", "-b", "0.0.0.0"] # 0.0.0.0 is required to connect to the container in development
    environment:
      # For HTTP Basic auth
      ADMIN_USERNAME: # admin
      ADMIN_PASSWORD: # password
      DB_HOST: db # Docker uses the name of the DB service as the hostname
      DB_PASSWORD: root
      DB_PORT: 3306
      DB_USERNAME: root
    ports:
      - 3000:3000
    volumes:
      - .:/rails
  job_queue:
    <<: *app
    command: ["./bin/rake", "solid_queue:start"]
    entrypoint: "./bin/docker-job-queue-entrypoint"
    ports: [] # No ports required
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
